services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=pastebin'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
#      - 'MYSQL_USER=myuser'
#      - 'MYSQL_PASSWORD=secret'
#    ports:
#      - '3306:3306'
#
  oracle-xe:
    image: 'gvenzl/oracle-xe:latest'
    environment:
      - 'ORACLE_DATABASE=pastebin'
      - 'ORACLE_PASSWORD=verysecret'
      - 'APP_USER=myuser'
      - 'APP_USER_PASSWORD=secret'
    ports:
      - '1521:1521'

  pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
#      - mysql
      - oracle-xe
